<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">&#13;
	<head> &#13;
		<meta name="viewport" content="width=device-width" />&#13;
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />&#13;
		<title>Sentimental.ly</title>&#13;
		&#13;
	</head>&#13;
	<body bgcolor="#FFFFFF" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; margin: 0; padding: 0;">&#13;
	 &#13;
		<table bgcolor="#2C3E50" style="width: 100%;">&#13;
			<tr>&#13;
				<td></td>&#13;
					<td style="display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto; padding: 0;">&#13;
						<div style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; max-width: 600px; display: block; margin: 0 auto; padding: 15px;">&#13;
							<table bgcolor="#2C3E50" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%; margin: 0; padding: 0;">&#13;
								<tr >&#13;
									<td style="	
												font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
												margin-bottom:15px; 
												font-weight:500; 
												font-size: 22px; 
												color:#FFFFFF;">
												<h7>Sentimental.ly</h7>
									</td><td align="right" ></td>&#13;
								</tr>&#13;
							</table>&#13;
						</div>&#13;
					</td>&#13;
				<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;"></td>&#13;
			</tr>&#13;
		</table> &#13;
	 &#13;
		<table style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%; margin: 0; padding: 0;">&#13;
			<tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">&#13;
				<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;"></td>&#13;
				<td bgcolor="#FFFFFF" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto; padding: 0;">&#13;
					<div style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; max-width: 600px; display: block; margin: 0 auto; padding: 15px;">&#13;
						<table style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%; margin: 0; padding: 0;">&#13;
							<tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">&#13;
								<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">&#13;
									<h3 style="font-family: 'HelveticaNeue-Light', 'Helvetica Neue Light', 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; line-height: 1.1; color: #2C3E50; font-weight: 500; font-size: 27px; margin: 0 0 15px; padding: 0;">Hi</h3>&#13;
									<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-weight: normal; font-size: 17px; line-height: 1.6; margin: 0 0 10px; padding: 0;color: #2C3E50;">&#13;
										Your lookup for <em>${entityName}</em> has completed!&#13;
									</p>&#13;
								 &#13;
									<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; line-height: 1.6; background-color: #ECF0F1; margin: 0 0 15px; padding: 15px; color: #2C3E50;">&#13;
										You can see the results if you follow <a href="${baseURL}/#/lookups/${lookupId}" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; color: #18BC9C; font-weight: bold; margin: 0; padding: 0;">this link.</a>&#13;
									</p>&#13;
								 &#13;
									<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; line-height: 1.6; margin: 0 0 10px; padding: 0;"><a href="${baseURL}/#/lookups/${lookupId}" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; color: #18BC9C; margin: 0; padding: 0;">${baseURL}/#/lookups/${lookupId}</a></p>&#13;
								</td>&#13;
							</tr>&#13;
						</table>&#13;
					</div> &#13;
				</td>&#13;
				<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;"></td>&#13;
			</tr>&#13;
		</table> &#13;
	 &#13;
		<table style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%; clear: both !important; margin: 0; padding: 0;">&#13;
			<tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">&#13;
				<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;"></td>&#13;
					<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto; padding: 0;">&#13;
					 &#13;
						<div style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; max-width: 600px; display: block; margin: 0 auto; padding: 15px;">&#13;
							<table style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%; margin: 0; padding: 0;">&#13;
								<tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">&#13;
									<td align="center" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">&#13;
									<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-weight: normal; font-size: 10px; line-height: 1.6; margin: 0 0 10px; padding: 0; color: #c1c1c1;">&#13;
										<h8 style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-weight: 100; font-size: 10px; color: #c1c1c1; margin: 0; padding: 0;">You will not recieve any more e-mails from us without making a new lookup on Sentimental.ly</h8>&#13;
									</p>&#13;
									</td>&#13;
								</tr>&#13;
							</table>&#13;
						</div> &#13;
					</td>&#13;
				<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;"></td>&#13;
			</tr>&#13;
		</table> &#13;
	</body>&#13;
</html>
